### ISSUE TITLE
The Visualization Web app seems to pause periodically on the browser

### ISSUE THREAD

**Issue by paloukari** [paloukari/TypeEdge.AnomalyDetection#8]

**Comment by ecthros** [comment]
I can't be completely sure what you're referring to, but I think the main bottlenecks are due to the following every time I draw new charts:
1. Creating new chart objects
2. Creating a new FFT object
3. Processing the FFT every time

I've addressed the first issue by creating globals for each chart object, and the second issue by recreating a FFT object only when the user changes the number of objects in the FFT. As a result, the framerate has increased significantly. However, once Archer implements the FFT in C#, I won't have to run any FFT calculations in JavaScript, which should help the framerate even more.
